// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/abuse-store.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest_Cause int32

const (
	PushRequest_ILLEGAL_CONTENT PushRequest_Cause = 0
	PushRequest_MALWARE         PushRequest_Cause = 1
	PushRequest_APP_ERROR       PushRequest_Cause = 2
	PushRequest_QUESTION        PushRequest_Cause = 3
)

// Enum value maps for PushRequest_Cause.
var (
	PushRequest_Cause_name = map[int32]string{
		0: "ILLEGAL_CONTENT",
		1: "MALWARE",
		2: "APP_ERROR",
		3: "QUESTION",
	}
	PushRequest_Cause_value = map[string]int32{
		"ILLEGAL_CONTENT": 0,
		"MALWARE":         1,
		"APP_ERROR":       2,
		"QUESTION":        3,
	}
)

func (x PushRequest_Cause) Enum() *PushRequest_Cause {
	p := new(PushRequest_Cause)
	*p = x
	return p
}

func (x PushRequest_Cause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushRequest_Cause) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_abuse_store_proto_enumTypes[0].Descriptor()
}

func (PushRequest_Cause) Type() protoreflect.EnumType {
	return &file_proto_abuse_store_proto_enumTypes[0]
}

func (x PushRequest_Cause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushRequest_Cause.Descriptor instead.
func (PushRequest_Cause) EnumDescriptor() ([]byte, []int) {
	return file_proto_abuse_store_proto_rawDescGZIP(), []int{1, 0}
}

type PushRequest_Source int32

const (
	PushRequest_MAIL PushRequest_Source = 0
	PushRequest_FORM PushRequest_Source = 1
)

// Enum value maps for PushRequest_Source.
var (
	PushRequest_Source_name = map[int32]string{
		0: "MAIL",
		1: "FORM",
	}
	PushRequest_Source_value = map[string]int32{
		"MAIL": 0,
		"FORM": 1,
	}
)

func (x PushRequest_Source) Enum() *PushRequest_Source {
	p := new(PushRequest_Source)
	*p = x
	return p
}

func (x PushRequest_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushRequest_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_abuse_store_proto_enumTypes[1].Descriptor()
}

func (PushRequest_Source) Type() protoreflect.EnumType {
	return &file_proto_abuse_store_proto_enumTypes[1]
}

func (x PushRequest_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushRequest_Source.Descriptor instead.
func (PushRequest_Source) EnumDescriptor() ([]byte, []int) {
	return file_proto_abuse_store_proto_rawDescGZIP(), []int{1, 1}
}

// The push response message containing
type PushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReply) Reset() {
	*x = PushReply{}
	mi := &file_proto_abuse_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReply) ProtoMessage() {}

func (x *PushReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_abuse_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReply.ProtoReflect.Descriptor instead.
func (*PushReply) Descriptor() ([]byte, []int) {
	return file_proto_abuse_store_proto_rawDescGZIP(), []int{0}
}

// The push request message
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      string                 `protobuf:"bytes,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Infohash      string                 `protobuf:"bytes,2,opt,name=infohash,proto3" json:"infohash,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Work          string                 `protobuf:"bytes,4,opt,name=work,proto3" json:"work,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Subject       string                 `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	Cause         PushRequest_Cause      `protobuf:"varint,9,opt,name=cause,proto3,enum=PushRequest_Cause" json:"cause,omitempty"`
	Source        PushRequest_Source     `protobuf:"varint,10,opt,name=source,proto3,enum=PushRequest_Source" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_abuse_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_abuse_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_abuse_store_proto_rawDescGZIP(), []int{1}
}

func (x *PushRequest) GetNoticeId() string {
	if x != nil {
		return x.NoticeId
	}
	return ""
}

func (x *PushRequest) GetInfohash() string {
	if x != nil {
		return x.Infohash
	}
	return ""
}

func (x *PushRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PushRequest) GetWork() string {
	if x != nil {
		return x.Work
	}
	return ""
}

func (x *PushRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *PushRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PushRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PushRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PushRequest) GetCause() PushRequest_Cause {
	if x != nil {
		return x.Cause
	}
	return PushRequest_ILLEGAL_CONTENT
}

func (x *PushRequest) GetSource() PushRequest_Source {
	if x != nil {
		return x.Source
	}
	return PushRequest_MAIL
}

// The check request message containing the infoHash
type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infohash      string                 `protobuf:"bytes,1,opt,name=infohash,proto3" json:"infohash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_abuse_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_abuse_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_abuse_store_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetInfohash() string {
	if x != nil {
		return x.Infohash
	}
	return ""
}

// The check response message containing existance flag
type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_proto_abuse_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_abuse_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_proto_abuse_store_proto_rawDescGZIP(), []int{3}
}

func (x *CheckReply) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_abuse_store_proto protoreflect.FileDescriptor

const file_proto_abuse_store_proto_rawDesc = "" +
	"\n" +
	"\x17proto/abuse-store.proto\"\v\n" +
	"\tPushReply\"\xa4\x03\n" +
	"\vPushRequest\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\tR\bnoticeId\x12\x1a\n" +
	"\binfohash\x18\x02 \x01(\tR\binfohash\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x12\n" +
	"\x04work\x18\x04 \x01(\tR\x04work\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12(\n" +
	"\x05cause\x18\t \x01(\x0e2\x12.PushRequest.CauseR\x05cause\x12+\n" +
	"\x06source\x18\n" +
	" \x01(\x0e2\x13.PushRequest.SourceR\x06source\"F\n" +
	"\x05Cause\x12\x13\n" +
	"\x0fILLEGAL_CONTENT\x10\x00\x12\v\n" +
	"\aMALWARE\x10\x01\x12\r\n" +
	"\tAPP_ERROR\x10\x02\x12\f\n" +
	"\bQUESTION\x10\x03\"\x1c\n" +
	"\x06Source\x12\b\n" +
	"\x04MAIL\x10\x00\x12\b\n" +
	"\x04FORM\x10\x01\"*\n" +
	"\fCheckRequest\x12\x1a\n" +
	"\binfohash\x18\x01 \x01(\tR\binfohash\"$\n" +
	"\n" +
	"CheckReply\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2W\n" +
	"\n" +
	"AbuseStore\x12\"\n" +
	"\x04Push\x12\f.PushRequest\x1a\n" +
	".PushReply\"\x00\x12%\n" +
	"\x05Check\x12\r.CheckRequest\x1a\v.CheckReply\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_proto_abuse_store_proto_rawDescOnce sync.Once
	file_proto_abuse_store_proto_rawDescData []byte
)

func file_proto_abuse_store_proto_rawDescGZIP() []byte {
	file_proto_abuse_store_proto_rawDescOnce.Do(func() {
		file_proto_abuse_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_abuse_store_proto_rawDesc), len(file_proto_abuse_store_proto_rawDesc)))
	})
	return file_proto_abuse_store_proto_rawDescData
}

var file_proto_abuse_store_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_abuse_store_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_abuse_store_proto_goTypes = []any{
	(PushRequest_Cause)(0),  // 0: PushRequest.Cause
	(PushRequest_Source)(0), // 1: PushRequest.Source
	(*PushReply)(nil),       // 2: PushReply
	(*PushRequest)(nil),     // 3: PushRequest
	(*CheckRequest)(nil),    // 4: CheckRequest
	(*CheckReply)(nil),      // 5: CheckReply
}
var file_proto_abuse_store_proto_depIdxs = []int32{
	0, // 0: PushRequest.cause:type_name -> PushRequest.Cause
	1, // 1: PushRequest.source:type_name -> PushRequest.Source
	3, // 2: AbuseStore.Push:input_type -> PushRequest
	4, // 3: AbuseStore.Check:input_type -> CheckRequest
	2, // 4: AbuseStore.Push:output_type -> PushReply
	5, // 5: AbuseStore.Check:output_type -> CheckReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_abuse_store_proto_init() }
func file_proto_abuse_store_proto_init() {
	if File_proto_abuse_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_abuse_store_proto_rawDesc), len(file_proto_abuse_store_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_abuse_store_proto_goTypes,
		DependencyIndexes: file_proto_abuse_store_proto_depIdxs,
		EnumInfos:         file_proto_abuse_store_proto_enumTypes,
		MessageInfos:      file_proto_abuse_store_proto_msgTypes,
	}.Build()
	File_proto_abuse_store_proto = out.File
	file_proto_abuse_store_proto_goTypes = nil
	file_proto_abuse_store_proto_depIdxs = nil
}
